index:
    path: /
    controller: App\Controller\SimplePageController::index

craftsmanship:
    path: /craftsmanship
    controller: App\Controller\SimplePageController::craftsmanship

smw:
    path: /smw
    controller: App\Controller\SimplePageController::smw

wikidata:
    path: /wikidata
    controller: App\Controller\SimplePageController::wikidata

gaming:
    path: /gaming
    controller: App\Controller\SimplePageController::page

open-source:
    path: /open-source
    controller: App\Controller\SimplePageController::page

services:
    path: /services
    controller: App\Controller\SimplePageController::page

redirects:
    path: /{page}
    controller: App\Controller\SimplePageController::redirects
    requirements:
        page: projects

project:
    path: /projects/{project}
    controller: App\Controller\SimplePageController::project

404:
    path: /{page}
    controller: App\Controller\SimplePageController::notFound
    requirements:
        page: ".+"

sitemap:
    path: sitemap.xml
    controller: App\Controller\SimplePageController::sitemap