index:
    path: /
    controller: App\Controller\SimplePageController::index

craftsmanship:
    path: /craftsmanship
    controller: App\Controller\SimplePageController::craftsmanship

smw:
    path: /semantic-mediawiki
    controller: App\Controller\SimplePageController::smw

mediawiki:
    path: /mediawiki
    controller: App\Controller\SimplePageController::page

wikidata:
    path: /wikidata
    controller: App\Controller\SimplePageController::wikidata

gaming:
    path: /gaming
    controller: App\Controller\SimplePageController::page

open-source:
    path: /open-source
    controller: App\Controller\SimplePageController::page

services:
    path: /services
    controller: App\Controller\SimplePageController::page

project:
    path: /projects/{project}
    controller: App\Controller\SimplePageController::project

sitemap:
    path: sitemap.xml
    controller: App\Controller\SimplePageController::sitemap

slides:
    path: /slides/{page}
    controller: App\Controller\SimplePageController::slides
    requirements:
        page: fun-architecture

404: # MUST BE LAST!
    path: /{page}
    controller: App\Controller\NotFoundController::notFound
    requirements:
        page: ".+"
