index:
    path: /
    controller: App\Controller\SimplePageController::index

simple:
    path: /{page}
    controller: App\Controller\SimplePageController::page

project:
    path: /projects/{project}
    controller: App\Controller\SimplePageController::project
